### ISSUE TITLE
All improvements are in the "to do" column of the project. Link in description

### ISSUE THREAD

**Issue by kojofosu** [kojofosu/SplitButton#1]
Link to project board:  https://github.com/users/kojofosu/projects/12

**Comment by pratik9315** [comment]
Hey I would like to work on one of open the issues listed in the to-do sections?

**Comment by kojofosu** [comment]
@pratik2315 , yes sure, go ahead. Open a pull request when you're done and I'll review and merge if it works.

**Comment by xtanion** [comment]
I would like to work on the issues from to-do section 😄

**Comment by kojofosu** [comment]
Anyone is welcome to partake . Just make a fork and create a pull request
when you're fone
